#!/bin/sh
#
###
## Customization done to base QCOW image:
#

pkg_add -I isc-bind-9.10.0pl2

#(cd; wget http://www.litech.org/radvd/dist/radvd-2.7.tar.bz2 &&
#    tar jxvf radvd-2.7.tar.bz2 && cd radvd-2.7 && ./configure && make && make install && cd ../ &&
#    rm -rf radvd-2.7 && rm -f radvd-2.7.tar.bz2)

[ -d /var/cache/bind ] || mkdir /var/cache/bind
cat > /var/cache/bind/badlist << \EOF
$TTL 1H
@                       SOA LOCALHOST. aaaa-only.example.com (1 1h 15m 30d 2h)
                        NS  LOCALHOST.
EOF
(for i in `seq 0 255`; do echo "8.0.0.0.$i.rpz-ip      CNAME   *."; done;
 echo "32.1.0.0.127.rpz-ip     CNAME   rpz-passthru.") >> /var/cache/bind/badlist

cat > /etc/named-nat64.conf << \EOF
options {
        port 1175;
        directory "/var/cache/bind";
        auth-nxdomain no;    # conform to RFC1035
        listen-on { none; };
        listen-on-v6 { ::1; };
        allow-query { any; };
        allow-recursion { any; };
        forwarders {
                2a02:6b8:0:3400::1 port 53;
        };
        forward only;
        preferred-glue AAAA;
        dns64 64:ff9b::/96 {
                suffix ::;
                clients { any; };
                mapped { !10/8; any; };
                exclude { 64:ff9b::/96; };
                break-dnssec yes;
        };
};
EOF

cat > /etc/named-aaaa-only.conf << \EOF
options {
        directory "/var/cache/bind";
        auth-nxdomain no;    # conform to RFC1035
        listen-on { none; };
        listen-on-v6 { any; };
        allow-query { any; };
        allow-recursion { any; };
        forwarders {
                ::1 port 1175;
        };
        forward only;
        response-policy { zone "badlist"; };
};
zone "badlist" {type master; file "badlist"; allow-query {none;}; };
EOF


[ -f /etc/sysctl.conf--orig ] || cp /etc/sysctl.conf /etc/sysctl.conf--orig
sed "s/net.inet6.ip6.accept_rtadv=1/net.inet6.ip6.accept_rtadv=0/" /etc/sysctl.conf--orig > /etc/sysctl.conf

cat > /etc/hostname.vio0 << \EOF
up
!ifconfig $if inet6 -autoconfprivacy -autoconf
!(PATH=$PATH:/usr/local/sbin:/usr/local/bin duid-uuid-update $if)
!/usr/local/sbin/dhcpcd -4 $if
!(while ifconfig $if inet6|grep tentative >/dev/null; do sleep 1; echo "waiting for linklocal on $if"; done)
!/usr/local/sbin/dhclient -6 -nw -pf /var/run/dhclient6.$if.pid -lf /var/db/dhclient6.$if.leases $if
!(PATH=$PATH:/usr/local/sbin:/usr/local/bin ndisc_update &)&
EOF

cat > /etc/hostname.vio1 << \EOF
up
!ifconfig $if inet6 -autoconfprivacy -autoconf
!(PATH=$PATH:/usr/local/sbin:/usr/local/bin duid-uuid-update $if)
!/usr/local/sbin/dhclient -4 -nw -pf /var/run/dhclient.$if.pid -lf /var/db/dhclient.$if.leases $if
!(while ifconfig $if inet6|grep tentative >/dev/null; do sleep 1; echo "waiting for linklocal on $if"; done)
!/usr/local/sbin/dhclient -6 -nw -pf /var/run/dhclient6.$if.pid -lf /var/db/dhclient6.$if.leases $if
EOF

[ -f /etc/pf.conf--orig ] || cp /etc/pf.conf /etc/pf.conf--orig

 
if ! grep ipv46_nat64_autoconf /etc/rc.local >/dev/null; then
    echo '(PATH=$PATH:/usr/local/sbin:/usr/local/bin ipv46_wait_for_defroute 4)' >>/etc/rc.local
    echo '(PATH=$PATH:/usr/local/sbin:/usr/local/bin ipv46_wait_for_defroute 6)' >>/etc/rc.local
    echo '(PATH=$PATH:/usr/local/sbin:/usr/local/bin ipv46_nat64_autoconf)' >>/etc/rc.local
fi
