#!/bin/bash
# chkconfig: 2345 9 90
### BEGIN INIT INFO
# Provides: cauth
# Required-Start: ptr sssd
# Defalt-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: CAUTH agent
### END INIT INFO#
. /etc/init.d/functions
if [ "$1" != "start" ]; then
   exit 0
fi
/usr/bin/agent.sh
