#!/bin/bash
# chkconfig: 2345 9 90
### BEGIN INIT INFO
# Provides: ptr
# Required-Start: defroute
# Defalt-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: IPv4/IPv6 PTR DNS records checks and signaling
### END INIT INFO#
. /etc/init.d/functions
if [ "$1" != "start" ]; then
   exit 0
fi
ipv46_wait_for_hostname_prt
