#!/usr/bin/env bash
export PATH=$PATH:/usr/local/sbin:/usr/local/bin

ME=${0##*/}

FDS="$(lsof -a -p $$ -d'^0-2,^255' 2>/dev/null|awk '{if($4~/^[0-9]+/){gsub(/[^0-9]/,"",$4);print $4}}')"
for fdd in $FDS; do
	eval "exec $fdd>&-"
done


ONEXIT="$1"

msg(){
    local P
    P="${ME}[$$]${i:+(try #$i)}"
    echo "$P:" "$1" >&2
    logger -t "$P" "$1"
}

ipv6_get_global(){
	ifconfig |awk '/^[^[:blank:]]+:/ {split($1, i, ":");E="";next}; $1=="lladdr" {E=$2;next}; {if($1=="inet6" && $2!~/%/ && i[1]!="lo0")print $2,i[1],E}'
}
ipv6_get_linklocal(){
	ifconfig |awk '/^[^[:blank:]]+:/ {split($1, i, ":");E="";next}; $1=="lladdr" {E=$2;next}; {if($1=="inet6" && $2~/%/ && i[1]!="lo0")print $2,i[1],E}'
}

is_def(){
	local ver ipv router iface ip
	for ver in $1; do
		ipv=$ver
		[ $ver -eq 4 ] && ipv=
		R="$(route -n get -inet$ipv default 2>/dev/null)"
		if [ $? -eq 0 ]; then
			router="$(echo "$R"|awk '{if($1=="gateway:")print $2}'|head -1)"
			iface="$(echo "$R"|awk '{if($1=="interface:")print $2}'|head -1)"
			ip="$(echo "$R"|awk '{if($1=="if" && $2=="address:")print $3}'|head -1)"
			if [ -n "$iface" -a -n "$ip" -a -n "router" ]; then
				echo "$iface $ver $ip $router"
			fi
		fi
	done
}

for i in `seq 12`; do
	####
	### Default routes
	#
	DR="$(is_def "4 6")"
	if [ -z "$DR" ]; then
		msg "No default route. waiting 5 sec"
		sleep 5
		continue
	fi
	msg "$DR"

	iface_dr_count=$(echo "$DR"|awk '{print $1}'|sort -u|grep -v '^$'|wc -l)
	dr_version_count=$(echo "$DR"|awk '{print $2}'|sort -u|grep -v '^$'|wc -l)
	dr_router_count=$(echo "$DR"|awk '{print $3}'|sort -u|grep -v '^$'|wc -l)

	if ! [ $iface_dr_count -gt 0 -a $iface_dr_count -lt 3 ] ||
	   ! [ $dr_version_count -eq 2 -a $dr_version_count -eq $dr_router_count ]; then
		msg "Waiting for default routes to assign."
		sleep 5
		continue
	fi

	ifaces_dr="$(echo "$DR"|awk '{print $1}'|sort -u|grep -v '^$')"
	ipv4_ip="$(echo "$DR"|awk '{if($2==4)print $3}'|sort -u|grep -v '^$'|head -1)"
	ipv4_iface="$(echo "$DR"|awk '{if($2==4)print $1}'|sort -u|grep -v '^$'|head -1)"
	ipv6_iface="$(echo "$DR"|awk '{if($2==6)print $1}'|sort -u|grep -v '^$'|head -1)"

	if [ -z "$ipv4_ip" ]; then
		msg "Waiting for IPv4"
		sleep 10
		continue
	fi

	ifaces_all="$(ifconfig |awk '/^[^[:blank:]]+:/ {split($1, i, ":");E="";next}; $1=="lladdr" {E=$2;next}; {if($1=="status:" && E!="")print i[1]}')"

	nat64_iface="$(echo "$ifaces_all"|grep -v "$ipv4_iface")"
	nat64_iface="${nat64_iface:-$ipv4_iface}"
	nat64_iface_count="$(echo "$nat64_iface"|wc -l)"
	if [ $nat64_iface_count -gt 1 ]; then
		msg "ERROR: NAT64 interface should be only one. Exiting"
		exit 2
	fi

	ipv6ll_ip=$(ipv6_get_ipv6ll_by_iface $nat64_iface)
	ipv6_ip="$(ipv6_get_global_permanent |awk -v iface=$nat64_iface '{if($2==iface)print $1}'|head -1)"
	ipv6_ip="${ipv6_ip:-$(ipv6_get_global |awk -v iface=$nat64_iface '{if($2==iface)print $1}'|head -1)}"
	if [ -z "$ipv6_ip" ]; then
		msg "Waiting for global IPv6 for $nat64_iface"
		sleep 5
		continue 2
	fi
	AS="pass in log on $nat64_iface inet6 from any to 64:ff9b::/96 af-to inet from $ipv4_ip"

	msg "              All Interfaces: $(echo $ifaces_all)"
	msg "    Default Route Interfaces: $(echo $ifaces_dr)"
	msg "IPv6 default route interface: $ipv6_iface"
	msg "IPv4 default route interface: $ipv4_iface"
	msg ""
	msg "  Translation IPv6 interface: $nat64_iface"
	msg "                 Public IPv4: $ipv4_ip"
	msg ""
	msg "   Router IPv6LL for NAT64 on $iface: ${ipv6ll_ip%%%*}"
	msg "     Public IPv6 for DNS64 on $iface: $ipv6_ip"
	msg ""

	msg "Applying nat64 rules"
	AS="pass in log on $nat64_iface inet6 from any to 64:ff9b::/96 af-to inet from $ipv4_ip"
	cat /etc/pf.conf--orig |sed "/#block in quick/ i \\
$AS \\
" > /etc/pf.conf--auto
	pfctl -f /etc/pf.conf--auto

	msg "Announcing NAT64 Route Information and DNS64 on $iface using RA-RIO"
	pkill rtadvd
	echo "$nat64_iface:raflags=#192:rltime#0:pinfoflags#0:mtu#1450:addr=\"64:ff9b::\":prefixlen#96:rtprefix=\"64:ff9b::\":rtplen#96:rtltime#1800:rdnss=\"$ipv6_ip\":" > /etc/rtadvd.conf--nat64
	rtadvd -s -c /etc/rtadvd.conf--nat64 $nat64_iface

	msg "Starting DNS64 AAAA-only server"
	pkill named
	sleep 3
	/usr/local/sbin/named -c /etc/named-nat64.conf
	/usr/local/sbin/named -c /etc/named-aaaa-only.conf

	msg ""
	msg "HINT: On the host you need to add NAT64 route and use DNS64 nameserver above"
	msg ""
	msg " To enable linux to listen for NAT64 route announce:"
	msg "   sysctl net.ipv6.conf.eth0.accept_ra_rt_info_max_plen=96"
	msg "        or"
	msg " To add static route:"
	msg "   ip r a 64:ff9b::/96 via ${ipv6ll_ip%%%*}%eth0"
	msg ""
	msg " Line to replace in resolv.conf:"
	msg "   nameserver $ipv6_ip"
	msg ""

	exit 0
done
