#!/bin/sh
PIDFILE="$(mktemp)"
CLEAN=
cleanup() {
 if [ -z "$CLEAN" ]; then
	kill `cat "$PIDFILE"` 2>/dev/null
	rm -f "$PIDFILE"
	CLEAN=yes
 fi
}
trap cleanup 0 1 2 15
(ip -6 monitor address & echo $! > "$PIDFILE")|
	sed -n "s;^[[:digit:]]\+:\s\+\([[:alnum:]]\+\)\s\+inet6\s\+\([[:alnum:]:]\+\)/[[:digit:]]\+\s\+scope global[[:blank:]]*$;\2 \1;;ta;b;:a p;ekill \$(cat $PIDFILE)"